# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_AW_CRASHDUMP) += sunxi-dump.o

sunxi-dump-y += sunxi-crashdump.o sunxi-dump2pc.o

sunxi-dump-$(CONFIG_AW_CRASHDUMP_KEY) += sunxi-crashdump-key.o

