# SPDX-License-Identifier: GPL-2.0
# Core module
obj-$(CONFIG_AVA_FB_TFT)             += fbtft.o
fbtft-y                          += fbtft-core.o fbtft-sysfs.o fbtft-bus.o fbtft-io.o

# drivers
obj-$(CONFIG_AVA_FB_TFT_ST7789V)     += fb_st7789v.o
