name: Merge Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  linux-5_10:
    runs-on: ubuntu-latest
    env:
      KERNEL_URL: https://cdn.kernel.org/pub/linux/kernel/v5.x/
      KERNEL_VERSION: linux-5.10.214
      KERNEL_BRANCH: linux-5.10
    steps:
    - uses: actions/checkout@v3
    - name: Set id
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Merge ${{env.KERNEL_BRANCH}}
      continue-on-error: true
      run: ./init.sh -u  ${{env.KERNEL_URL}} -v  ${{env.KERNEL_VERSION}} -b  ${{env.KERNEL_BRANCH}}

    - name: Push changes ${{env.KERNEL_BRANCH}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SY_PAT }}
        branch: ${{env.KERNEL_BRANCH}}
        directory: kernel/dst/${{env.KERNEL_BRANCH}}/${{env.KERNEL_BRANCH}}
        force: true

  linux-5_10_oe:
    runs-on: ubuntu-latest
    env:
      KERNEL_URL: https://gitee.com/openeuler/kernel.git
      KERNEL_VERSION: openEuler-22.03-LTS-SP2
      KERNEL_BRANCH: linux-5.10-oe
    steps:
    - uses: actions/checkout@v3
    - name: Set id
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Merge ${{env.KERNEL_BRANCH}}
      continue-on-error: true
      run: ./init.sh -u  ${{env.KERNEL_URL}} -v  ${{env.KERNEL_VERSION}} -b ${{env.KERNEL_BRANCH}} -d GIT

    - name: Push changes ${{env.KERNEL_BRANCH}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SY_PAT }}
        branch: ${{env.KERNEL_BRANCH}}
        directory: kernel/dst/${{env.KERNEL_BRANCH}}/${{env.KERNEL_BRANCH}}
        force: true

  linux-5_15:
    runs-on: ubuntu-latest
    env:
      KERNEL_URL: https://cdn.kernel.org/pub/linux/kernel/v5.x/
      KERNEL_VERSION: linux-5.15.161
      KERNEL_BRANCH: linux-5.15
    steps:
    - uses: actions/checkout@v3
    - name: Set id
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Merge ${{env.KERNEL_BRANCH}}
      continue-on-error: true
      run: ./init.sh -u  ${{env.KERNEL_URL}} -v  ${{env.KERNEL_VERSION}} -b  ${{env.KERNEL_BRANCH}}

    - name: Push changes ${{env.KERNEL_BRANCH}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SY_PAT }}
        branch: ${{env.KERNEL_BRANCH}}
        directory: kernel/dst/${{env.KERNEL_BRANCH}}/${{env.KERNEL_BRANCH}}
        force: true

  linux-6_1_aosp:
    runs-on: ubuntu-latest
    env:
      KERNEL_URL: https://android.googlesource.com/kernel/common.git/+archive/refs/heads/
      KERNEL_VERSION: android14-6.1-2023-10
      KERNEL_BRANCH: linux-6.1-aosp
    steps:
    - uses: actions/checkout@v3
    - name: Set id
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Merge ${{env.KERNEL_BRANCH}}
      continue-on-error: true
      run: ./init.sh -u  ${{env.KERNEL_URL}} -v ${{env.KERNEL_VERSION}} -b ${{env.KERNEL_BRANCH}} -t AOSP

    - name: Push changes ${{env.KERNEL_BRANCH}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SY_PAT }}
        branch: ${{env.KERNEL_BRANCH}}
        directory: kernel/dst/${{env.KERNEL_BRANCH}}/${{env.KERNEL_BRANCH}}
        force: true

  Sync-to-Gitee:
    runs-on: ubuntu-latest
    needs: [linux-5_10, linux-5_10_oe, linux-5_15, linux-6_1_aosp]
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: https://github.com/AvaotaSBC/linux.git
          destination-repo: git@gitee.com:avaotasbc/linux.git
