name: Merge Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  merge:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set id
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Merge Linux 5.15
      continue-on-error: true
      run: ./init.sh -u https://cdn.kernel.org/pub/linux/kernel/v5.x/ -v linux-5.15.154 -b linux-5.15

    - name: Push changes Linux 5.15
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: linux-5.15
        directory: kernel/dst/linux-5.15/linux-5.15
        force: true
