name: Merge Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set id
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

  linux-5_10:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      KERNEL_URL: https://cdn.kernel.org/pub/linux/kernel/v5.x/
      KERNEL_VERSION: linux-5.10.214
      KERNEL_BRANCH: linux-5.10
    steps:
    - uses: actions/checkout@v3

    - name: Merge ${{env.KERNEL_BRANCH}}
      continue-on-error: true
      run: ./init.sh -u  ${{env.KERNEL_URL}} -v  ${{env.KERNEL_VERSION}} -b  ${{env.KERNEL_BRANCH}}

    - name: Push changes ${{env.KERNEL_BRANCH}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SY_PAT }}
        branch: ${{env.KERNEL_BRANCH}}
        directory: kernel/dst/${{env.KERNEL_BRANCH}}/${{env.KERNEL_BRANCH}}
        force: true
  
  linux-5_15:
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      KERNEL_URL: https://cdn.kernel.org/pub/linux/kernel/v5.x/
      KERNEL_VERSION: linux-5.15.154
      KERNEL_BRANCH: linux-5.15
    steps:
    - uses: actions/checkout@v3

    - name: Merge ${{env.KERNEL_BRANCH}}
      continue-on-error: true
      run: ./init.sh -u  ${{env.KERNEL_URL}} -v  ${{env.KERNEL_VERSION}} -b  ${{env.KERNEL_BRANCH}}

    - name: Push changes ${{env.KERNEL_BRANCH}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SY_PAT }}
        branch: ${{env.KERNEL_BRANCH}}
        directory: kernel/dst/${{env.KERNEL_BRANCH}}/${{env.KERNEL_BRANCH}}
        force: true
